version: "3"

services:
  web:
    container_name: rails_docker
    build: .
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
      - "35729:35729"
    working_dir: /code
    volumes:
      - ./:/code:z

  database:
    container_name: rails_db
    image: bitnami/postgresql:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - demo_data:/bitnami/postgresql

  # Access pgadmin at localhost:5050 (see env file for login info)
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:5050"

volumes:
  demo_data:

# This is to allow docker to work properly on a VPN.
# Can be safely removed if not needed
networks:
  default:
    external:
      name: localdev
